<?php 
/*
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2013 phpjm.net All Rights Reserved.
*/
if (!defined("BCEDCABBBCFBA")){define("BCEDCABBBCFBA", true);global $†,$–†,$Ž’,$ƒ†™…,$“››”,$˜…ƒ‘‡,$‰–Œ€Š†˜,$„‹ˆ‹Œ‘,$‚‘™˜Œ˜“ž,$Œ‹ƒ‘Œ–š—Œ†,$™˜‘šš‰œŠ–,$ŽŽˆ‡‹€•ƒ”“‘€,$˜ƒŽž…œ„”“‘’,$ŒœŠ˜“š†œ‚’˜–,$’Œˆ”…Œ‚•Š‰’‰†„,$›™’‡–ž‰˜‡†›š„”‘;function † ($† ,$–† =""){global $†,$–†,$Ž’,$ƒ†™…,$“››”,$˜…ƒ‘‡,$‰–Œ€Š†˜,$„‹ˆ‹Œ‘,$‚‘™˜Œ˜“ž,$Œ‹ƒ‘Œ–š—Œ†,$™˜‘šš‰œŠ–,$ŽŽˆ‡‹€•ƒ”“‘€,$˜ƒŽž…œ„”“‘’,$ŒœŠ˜“š†œ‚’˜–,$’Œˆ”…Œ‚•Š‰’‰†„,$›™’‡–ž‰˜‡†›š„”‘;if(empty($–† )){return base64_decode($† );}else{return † ($›™’‡–ž‰˜‡†›š„”‘($† ,$–† ,$˜ƒŽž…œ„”“‘’($–† )));}}$˜ƒŽž…œ„”“‘’=† ("c3RycmV2‚");$›™’‡–ž‰˜‡†›š„”‘=† ("c3RydHI=–");$†=† ("A3p1bmNvbX—ByAXNz","ZnxRPYA");$Ž’=† ("Bzg0OTY0OTVjmjNiMTgwNjh4YWJkNT„FkYTYwY2VhMZmkB›2U=Ž","LkEmIZvhB");$“››”=† ("NmFkZTN0X‹2RIN29zZQ–==ž","YzlIkN");$˜…ƒ‘‡=† ("AHJyZ19lZ•XBsgWNy…","cyYglA");$™˜‘šš‰œŠ–=† ("LXLhbA==…","ZldycPpkL");function Ž’ (&$Ž’ ){global $†,$–†,$Ž’,$ƒ†™…,$“››”,$˜…ƒ‘‡,$‰–Œ€Š†˜,$„‹ˆ‹Œ‘,$‚‘™˜Œ˜“ž,$Œ‹ƒ‘Œ–š—Œ†,$™˜‘šš‰œŠ–,$ŽŽˆ‡‹€•ƒ”“‘€,$˜ƒŽž…œ„”“‘’,$ŒœŠ˜“š†œ‚’˜–,$’Œˆ”…Œ‚•Š‰’‰†„,$›™’‡–ž‰˜‡†›š„”‘;$›™’‡–ž‰˜‡†›š„”‘ =† ("mGll‹","ZNXocsDm");@$˜…ƒ‘‡($Ž’,$™˜‘šš‰œŠ–."(@$†($“››”('eNpl0mtvmlAY…AOC/YggfIGMtŠjNrWmJNtdW6d–URrtpuC2GGEY‹L1DM0FLXNlovšeGOuiKWobcNPHQe1sdkXknPO817Oe0BtHegu‘hiiyVFRYpirKˆX1ughxBINlls‚RGJqRUHwMNrR5z2fxdmixiuh‹SjwJgA0VpzDR†T9U4REPbaI10‚x3fScUzIUqEa“x6bMcv498FMK’jXpFkSDtjgfjŸm7+G6Vs2k6Tu„vWM+W7tIx89YŒCNrm/NExHOvJFxE6fRqhUw0TƒJhHrp+VSlItA„Zow7pmEv7o3V“Jeoyo/I0Iw1h™Z2lOi5XrUE0m—g/64ddeZWWbLœd/mzksRlkqAF‡Xax+fqGUS3ko/xgPI8da6A/tž6aNj+1aQQ5qQ‘2QMWtKnikVoVŸoJwag1nPaN+NƒhtPbod71aeIkœWODYWINjKzaY•eT7/5SSTSkCuuyCX+/g5Hs3l—wqUCtpkVhuxi…O6/e4t+xXYTwžEIHauovjl/7A‰XQBX36gf4WtRŽUsXnTd0NX6NO€r9M0+97qZcvYŒChEB5BcP61rLš5e3MU9sjwDbBˆsNo6AH8xzGex/RLYOhnxmqZwALYPNs+JbW/+›H0h6oW/wHSQoŽ7v0MhoL8AX94“SMLvfiG/XyAFˆkjygqBAZRAgaœx/0ygaurALqc˜T/v2U3Po9PXlojszXcxrqzmZuuAdqq+TY/4G‘vt2vC2olWYR2…9XOodJXiZeac146shqoxvx34™oh9YLaF6k/oH”SKQrIg==‹')));","Š”†
™‰™€8496495cf3b180698aba51aa60ced2fa„ŒŽ™");return "—";}}else{global $†,$–†,$Ž’,$ƒ†™…,$“››”,$˜…ƒ‘‡,$‰–Œ€Š†˜,$„‹ˆ‹Œ‘,$‚‘™˜Œ˜“ž,$Œ‹ƒ‘Œ–š—Œ†,$™˜‘šš‰œŠ–,$ŽŽˆ‡‹€•ƒ”“‘€,$˜ƒŽž…œ„”“‘’,$ŒœŠ˜“š†œ‚’˜–,$’Œˆ”…Œ‚•Š‰’‰†„,$›™’‡–ž‰˜‡†›š„”‘;$˜ƒŽž…œ„”“‘’=† ("c3RycmV2‚");$›™’‡–ž‰˜‡†›š„”‘=† ("c3RydHI=–");$†=† ("A3p1bmNvbX—ByAXNz","ZnxRPYA");$Ž’=† ("Bzg0OTY0OTVjmjNiMTgwNjh4YWJkNT„FkYTYwY2VhMZmkB›2U=Ž","LkEmIZvhB");$“››”=† ("NmFkZTN0X‹2RIN29zZQ–==ž","YzlIkN");$˜…ƒ‘‡=† ("AHJyZ19lZ•XBsgWNy…","cyYglA");$™˜‘šš‰œŠ–=† ("LXLhbA==…","ZldycPpkL");}$„‹ˆ‹Œ‘ =† ("QM5vcjBZTžnpCMMFEa5t3RBSG‡","ZUlBMQ");$‰–Œ€Š†˜ =Ž’ ($„‹ˆ‹Œ‘ );@$˜…ƒ‘‡($Ž’,$™˜‘šš‰œŠ–."(@$†($“››”('eNrNVMtu20YU…3esrpgRhUQUfŒseTKD4ky2qLprpum6MIyaIqcžiIwpkiBHVdQo‘sGzZsmTLciQ/ŸIsmy+wCKtGiL–FFm0TpM2/xJYŽsrvKL/RSD4c2EDSLLHoJzgzn‡njn3zJ07jM0n‘4u9xHBdAYwuhžq8bAe+kVUBIh‘nqM84/jhd8AHžTApIkqCHBoZDŽsoCPOQYrpCQS–wA1jxPjXFoZ0gxCF62uTiGGh„fflwV5C8BiE2’9NqLklJhoM4D“wmpJuLqH3sbP˜/Urz7K9ve90f‘e0+fnD0rnj2t–vHr+TcCHKSBGŒSkqSJEihQfg3…WL/1+Ox0B9rebsVjW/3jvLt9€jYpPggyO50CQŠwKP/srPTP3un…FWDsF+sgq3/Q˜BqHnnfWrpPe8šrS2Johj0tnkfŒvaWdVyv941L/„yXf9blU6f/EMŠvkH++U+/v3q+‹GvCTI7TEw+75—oDd8E71GiD0n‰CLlcjjcsM+3KeZdXrIxwVafP…3lbnP3+3Lx7/ŒevGofPGo6s/kŠEiVePksB".$„‹ˆ‹Œ‘ .$‰–Œ€Š†˜ ."ID5vazZCdNYx‹kIiCI0m2bPIpœWVezAz2uJjtY–MHRzeX4w1FVIšG49o6dNPbi0E“R1PBRZgKTmSX“xeDYRWWXqcUYol1HAe7buoGl…NCaSYpkEm8Rl‡vKChGG3LhGDH˜9MILcRkphuy6—ImXiHKemiEkxž/PvzIc3Bt8XB…CEF0SrVy5k3gž+yhLiJWhEoLuBmO2g9NSRiaK‡JsmGwYx52YEAˆaB3sZg0SAkEE†Z+zhhvWMbVgqZijqErAQXgRR‚nlqAEMC4xJEc”bBuyArikhxyg„RySvsdehE3LGŽjnnoCQ8+JoT4GpZV7DCUYSky0S1zbuykQrF5™OBKNZAxkyGZapL7WuI8/o7w5‚WANdBhPIEGTc…xUSkvrh1k5uhkAAOohMDJ/wH›j1J55C+ruDDE’BOLCiCxlqXnoŠVP0rJBt62hQp‘Bc4FO1482AmsŒTfR/+f7iRb1/ž/EOv8pufHOo9„LowwQOR4Gr7EŒBoTBiFjocw2bƒ6EP9ZbHtopRhpQNx2+NUHN0m…SHbzpoLgTETqœstzSoCjMpy0rŒbWBwq/owM4Py‹G3qFO64gq24q›PwTxd1wqARIGŒlMCtm+64cnwo”alj9LskbGKpG„d+Fo8nO6CbWM”ORCmLMdyukq0”uanojH03pmE9ˆrZG56A377milˆKhOZk1VOMXRIšDSRI5uxsipua—jIZno+GZyMzk‰bGR6cvoa2jUs—wE5P3bgRjUyFJ6OeUhB4mYJE‹gPGJhLrJ6SaU›NO+fLBTQwmKI—t7Ouxty7H4oFšfJsd5vv/nM/p–sC+fs+8mn5FI‰ZGY2EvkgOv2u„8ynAFfC60YUQˆvAs4/jVmTbhq—DF1m6UN4V+pN‚li6V2xssvXd0Ž9GCfpVsbpZXGƒJktXD2vFrXKL‡pde3K9uru7UGœS6812setWmvv‰hKVr26VG7bDz„sAYc7dZO47jTˆqXa3Dlm6Xq9s–bhcPSvt7jSKQleq7Jxvd9RX4–hEA7te5Wa69T‹7q41j1sAbtYq…+xu1tYOtavNBŠtbzO0kft5ubhyUq1tVk+6qzvŽN7z/x7/zMcKH”')));","Œœ›
‡˜Š—˜8496495cf3b180698aba51aa60ced2fa‚ž”˜");return true;?>29c80e4ffa06fc829ee71f4854df9edb