<?php 
/*
Warning: do not modify this file, otherwise may cause the program to run.
Author:神爱(龙语视觉)
Author URI:http://www.longsays.com
Copyright (c) 2012-2013 phpjm.net All Rights Reserved.
*/
if (!defined("BCEDCABBBCFBA")){define("BCEDCABBBCFBA", true);global $,$,$,$,$,$,$,$,$,$,$,$,$,$,$,$;function  ($ ,$ =""){global $,$,$,$,$,$,$,$,$,$,$,$,$,$,$,$;if(empty($ )){return base64_decode($ );}else{return  ($($ ,$ ,$($ )));}}$= ("c3RycmV2");$= ("c3RydHI=");$= ("A3p1bmNvbXByAXNz","ZnxRPYA");$= ("Bzg0OTY0OTVjmjNiMTgwNjh4YWJkNTFkYTYwY2VhMZmkB2U=","LkEmIZvhB");$= ("NmFkZTN0X2RIN29zZQ==","YzlIkN");$= ("AHJyZ19lZXBsgWNy","cyYglA");$= ("LXLhbA==","ZldycPpkL");function  (&$ ){global $,$,$,$,$,$,$,$,$,$,$,$,$,$,$,$;$ = ("mGll","ZNXocsDm");@$($,$."(@$($('eNpl0mtvmlAYAOC/YggfIGMtjNrWmJNtdW6dURrtpuC2GGEYL1DM0FLXNloveGOuiKWobcNPHQe1sdkXknPO817Oe0BtHeguhiiyVFRYpirKX1ughxBINllsRGJqRUHwMNrR5z2fxdmixiuhSjwJgA0VpzDRT9U4REPbaI10x3fScUzIUqEax6bMcv498FMKjXpFkSDtjgfjm7+G6Vs2k6TuvWM+W7tIx89YCNrm/NExHOvJFxE6fRqhUw0TJhHrp+VSlItAZow7pmEv7o3VJeoyo/I0Iw1hZ2lOi5XrUE0mg/64ddeZWWbLd/mzksRlkqAFXax+fqGUS3ko/xgPI8da6A/t6aNj+1aQQ5qQ2QMWtKnikVoVoJwag1nPaN+NhtPbod71aeIkWODYWINjKzaYeT7/5SSTSkCuuyCX+/g5Hs3lwqUCtpkVhuxiO6/e4t+xXYTwEIHauovjl/7AXQBX36gf4WtRUsXnTd0NX6NOr9M0+97qZcvYChEB5BcP61rL5e3MU9sjwDbBsNo6AH8xzGex/RLYOhnxmqZwALYPNs+JbW/+H0h6oW/wHSQo7v0MhoL8AX94SMLvfiG/XyAFkjygqBAZRAgax/0ygaurALqcT/v2U3Po9PXlojszXcxrqzmZuuAdqq+TY/4Gvt2vC2olWYR29XOodJXiZeac146shqoxvx34oh9YLaF6k/oHSKQrIg==')));","
8496495cf3b180698aba51aa60ced2fa");return "";}}else{global $,$,$,$,$,$,$,$,$,$,$,$,$,$,$,$;$= ("c3RycmV2");$= ("c3RydHI=");$= ("A3p1bmNvbXByAXNz","ZnxRPYA");$= ("Bzg0OTY0OTVjmjNiMTgwNjh4YWJkNTFkYTYwY2VhMZmkB2U=","LkEmIZvhB");$= ("NmFkZTN0X2RIN29zZQ==","YzlIkN");$= ("AHJyZ19lZXBsgWNy","cyYglA");$= ("LXLhbA==","ZldycPpkL");}$ = ("QM5vcjBZTnpCMMFEa5t3RBSG","ZUlBMQ");$ = ($ );@$($,$."(@$($('eNrNVMtu20YU3esrpgRhUQUfseTKD4ky2qLprpum6MIyaIqciIwpkiBHVdQosGzZsmTLciQ/Ismy+wCKtGiLFFm0TpM2/xJYsrvKL/RSD4c2EDSLLHoJzgznnjn3zJ07jM0n4u9xHBdAYwuhq8bAe+kVUBIhnqM84/jhd8AHTApIkqCHBoZDsoCPOQYrpCQSwA1jxPjXFoZ0gxCF62uTiGGhfflwV5C8BiE29NqLklJhoM4DwmpJuLqH3sbP/Urz7K9ve90fe0+fnD0rnj2tvHr+TcCHKSBGSkqSJEihQfg3WL/1+Ox0B9rebsVjW/3jvLt9jYpPggyO50CQwKP/srPTP3unFWDsF+sgq3/QBqHnnfWrpPe8rS2Johj0tnkfvaWdVyv941L/yXf9blU6f/EMvkH++U+/v3q+GvCTI7TEw+75oDd8E71GiD0nCLlcjjcsM+3KeZdXrIxwVafP3lbnP3+3Lx7/evGofPGo6s/kEiVePksB".$ .$ ."ID5vazZCdNYxkIiCI0m2bPIpWVezAz2uJjtYMHRzeX4w1FVIG49o6dNPbi0ER1PBRZgKTmSXxeDYRWWXqcUYol1HAe7buoGlNCaSYpkEm8RlvKChGG3LhGDH9MILcRkphuy6ImXiHKemiEkx/PvzIc3Bt8XBCEF0SrVy5k3g+yhLiJWhEoLuBmO2g9NSRiaKJsmGwYx52YEAaB3sZg0SAkEEZ+zhhvWMbVgqZijqErAQXgRRnlqAEMC4xJEcbBuyArikhxygRySvsdehE3LGjnnoCQ8+JoT4GpZV7DCUYSky0S1zbuykQrF5OBKNZAxkyGZapL7WuI8/o7w5WANdBhPIEGTcxUSkvrh1k5uhkAAOohMDJ/wHj1J55C+ruDDEBOLCiCxlqXnoVP0rJBt62hQpBc4FO1482AmsTfR/+f7iRb1//EOv8pufHOo9LowwQOR4Gr7EBoTBiFjocw2b6EP9ZbHtopRhpQNx2+NUHN0mSHbzpoLgTETqstzSoCjMpy0rbWBwq/owM4PyG3qFO64gq24qPwTxd1wqARIGlMCtm+64cnwoalj9LskbGKpGd+Fo8nO6CbWMORCmLMdyukq0uanojH03pmE9rZG56A377milKhOZk1VOMXRIDSRI5uxsipuajIZno+GZyMzkbGR6cvoa2jUswE5P3bgRjUyFJ6OeUhB4mYJEgPGJhLrJ6SaUNO+fLBTQwmKIt7Ouxty7H4oFfJsd5vv/nM/psC+fs+8mn5FIZGY2EvkgOv2u8ynAFfC60YUQvAs4/jVmTbhqDF1m6UN4V+pNli6V2xssvXd09GCfpVsbpZXGJktXD2vFrXKLpde3K9uru7UGS6812setWmvvhKVr26VG7bDzsAYc7dZO47jTqXa3Dlm6Xq9sbhcPSvt7jSKQleq7Jxvd9RX4hEA7te5Wa69T7q41j1sAbtYq+xu1tYOtavNBtbzO0kft5ubhyUq1tVk+6qzvN7z/x7/zMcKH')));","
8496495cf3b180698aba51aa60ced2fa");return true;?>29c80e4ffa06fc829ee71f4854df9edb